window.replit = {
  secrets: {
    FIREBASE_API_KEY: 'REPLIT_SECRET_FIREBASE_API_KEY',
    FIREBASE_AUTH_DOMAIN: 'REPLIT_SECRET_FIREBASE_AUTH_DOMAIN',
    FIREBASE_PROJECT_ID: 'REPLIT_SECRET_FIREBASE_PROJECT_ID',
    FIREBASE_STORAGE_BUCKET: 'REPLIT_SECRET_FIREBASE_STORAGE_BUCKET',
    FIREBASE_MESSAGING_SENDER_ID: 'REPLIT_SECRET_FIREBASE_MESSAGING_SENDER_ID',
    FIREBASE_APP_ID: 'REPLIT_SECRET_FIREBASE_APP_ID',
    FIREBASE_MEASUREMENT_ID: 'REPLIT_SECRET_FIREBASE_MEASUREMENT_ID',
  }
};
